source 'https://bitbucket.org/omegarinc/cocoapods-specs.git' # private spec repo
source 'https://github.com/CocoaPods/Specs.git' # master cocoapods spec repo

use_frameworks!

target 'ORCommonCode-Swift_Example', :exclusive => true do
  pod 'ORCommonCode-Swift', :path => '../'
end

target 'ORCommonCode-Swift_Tests', :exclusive => true do
  pod 'ORCommonCode-Swift', :path => '../'

  
end
